<?php

return [
  'api_key' => env('API_KEY', 'NONE'),
  'app_debug' => env('APP_DEBUG', 'NONE'),
  'api_url' => env('API_URL', 'NONE'),
  'customer_invoice' => env('CUSTOMER_INVOICE', 'NONE'),
  'surat_jalan' => env('SURAT_JALAN','NONE'),
  'detail_customer'=>env('DETAIL_CUSTOMER','NONE'),
  'add_customer_from_sj'=>env('ADD_CUSTOMER_FROM_SJ','NONE'),
  'add_do_dtl' => env('ADD_DO_DTL','NONE'),
  'detail_invoice'=> env('DETAIL_INVOICE','NONE'),
  'ttf_arh'=>env('TTF_ARH','NONE'),
  'ttf_arl'=>env('TTF_ARL','NONE'),
  'ttf_entry'=>env('TTF_ENTRY','NONE'),
  'customer'=>env('CUSTOMER','NONE'),
  'customer_file'=>env('CUSTOMER_FILE','NONE'),
  'customer_status'=>env('CUSTOMER_STATUS','NONE'),
  'maintain'=>env('MAINTAIN','NONE'),
  'list_standart'=>env('LIST_STANDART','NONE'),
  'list_due'=>env('LIST_DUE','NONE'),
  'list_item_standart'=>env('LIST_ITEM_STANDART','NONE'),
  'list_item_hartana'=>env('LIST_ITEM_HARTANA','NONE'),
  'list_dn'=>env('LIST_DN','NONE'),
  'aged_receivables'=>env('AGED_RECEIVABLES','NONE'),
  'ar_statements'=>env('AR_STATEMENTS','NONE'),
  'ar_statements_ii'=>env('AR_STATEMENTS_II','NONE'),
  'ags_customer_interest'=>env('AGS_CUSTOMER_INTEREST','NONE'),
  'ags_sales_interest'=>env('AGS_SALES_INTEREST','NONE'),
  'ags_last_payment'=>env('AGS_LAST_PAYMENT','NONE'),
  'customer_ledger_total'=>env('CUSTOMER_LEDGER_TOTAL','NONE'),
  'customer_ledger_date'=>env('CUSTOMER_LEDGER_DATE','NONE'),
  'customer_ledger_customer'=>env('CUSTOMER_LEDGER_CUSTOMER','NONE'),
  'best_products'=>env('BEST_PRODUCTS','NONE'),
  'best_customer'=>env('BEST_CUSTOMER','NONE'),
  'invoice_do_item'=>env('INVOICE_DO_ITEM','NONE'),
  'rekapitulasi_i'=>env('REKAPITULASI_I','NONE'),
  'rekapitulasi_ii'=>env('REKAPITULASI_II','NONE'),
  'financial'=>env('FINANCIAL','NONE'),
  'umur_sj'=>env('UMUR_SJ','NONE'),
  'penjualan'=>env('PENJUALAN','NONE'),
  'list_delivered_hartana'=>env('LIST_DELIVERED_HARTANA','NONE'),
  'setup_ar'=>env('SETUP_AR','NONE'),
  'modify_po'=>env('MODIFY_PO','NONE'),
  'modify_dn'=>env('MODIFY_DN','NONE'),
];
?>